# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cian Conway - Software Engineer
email: cian.conway@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer with a B.Eng. Computer Engineering from 
  The University of Limerick, currently living in Washington DC 
  working for Industry Dive in the digital B2B media sector in a 
  full stack web development role.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cianconway.tech" # the base hostname & protocol for your site
twitter_username: cianconway
github_username:  cianconway

# Build settings
markdown: kramdown
